name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "Visual Studio 16 2019"
            targetarch: x64
          - os: windows-latest
            generator: "Visual Studio 16 2019"
            targetarch: win32

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G ${{matrix.generator}} -A ${{matrix.targetarch}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      