name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            generator: "Visual Studio 16 2019"
            targetplatform: "Windows"
            targetapi: ""
            targetarch: x64
          - os: windows-latest
            generator: "Visual Studio 16 2019"
            targetplatform: "WindowsStore"
            targetapi: "10.0"
            targetarch: x64
          - os: macos-latest
            generator: "Xcode"
            targetplatform: "darwin"
            targetapi: ""
            targetarch: ""
          - os: ubuntu-latest
            generator: "Unix Makefiles"
            targetplatform: ""
            targetapi: ""
            targetarch: ""

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake (Visual Studio)
      if: ${{ matrix.generator == 'Visual Studio 16 2019' }}
      run: cmake -B ${{ github.workspace }}/build -G "${{ matrix.generator }}" -A "${{ matrix.targetarch }}" -DCMAKE_SYSTEM_NAME="${{ matrix.targetplatform }}" -DCMAKE_SYSTEM_VERSION="${{ matrix.targetapi }}" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"

    - name: Configure CMake (XCode)
      if: ${{ matrix.generator == 'XCode' }}
      run: cmake -B ${{ github.workspace }}/build -G "${{ matrix.generator }}" -DCMAKE_SYSTEM_NAME="${{ matrix.targetplatform }}" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"

    - name: Configure CMake (Unix Makefiles)
      if: ${{ matrix.generator == 'Unix Makefiles' }}
      run: cmake -B ${{ github.workspace }}/build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      